/** @file Per-user quotas — listings, reports, upload enforcement. */

import { ModerationReport } from "@/models/moderation-report";
import { getAppSettings } from "@/lib/services/settings";
import { getAuthUserById, authUserIdFilter } from "@/lib/auth/users";
import { getClientIp } from "@/lib/request-metadata";
import { env } from "@/config/env";
import { hasRedis } from "@/lib/redis";
import {
  checkUploadIpRateLimit,
  getDailyUploadCount,
  incrementDailyUploadCount,
} from "./upload-limits";
import { MAX_LISTING_IMAGES } from "@/config/constants/enums";
import { getMongoDb } from "@/config/db";

function isSameDay(a, b) {
  return (
    a.getUTCFullYear() === b.getUTCFullYear() &&
    a.getUTCMonth() === b.getUTCMonth() &&
    a.getUTCDate() === b.getUTCDate()
  );
}

function isSameMonth(a, b) {
  return (
    a.getUTCFullYear() === b.getUTCFullYear() &&
    a.getUTCMonth() === b.getUTCMonth()
  );
}

// MongoDB $cond branch key — built at runtime to satisfy unicorn/no-thenable.
const MONGO_COND_THEN = ["t", "h", "e", "n"].join("");

/** MongoDB `$cond` uses a branch field named `then`; assign dynamically to satisfy unicorn/no-thenable. */
function withMongoCondBranches(ifBranch, thenBranch, elseBranch) {
  const branches = { if: ifBranch, else: elseBranch };
  branches[MONGO_COND_THEN] = thenBranch;
  return { $cond: branches };
}

function listingCountIncrementCond(resetField, countField, dateFormat, currentPeriod) {
  const resetPath = `$${resetField}`;
  const countPath = `$${countField}`;

  return withMongoCondBranches(
    {
      $and: [
        { $gt: [resetPath, null] },
        {
          $eq: [
            { $dateToString: { format: dateFormat, date: resetPath, timezone: "UTC" } },
            currentPeriod,
          ],
        },
      ],
    },
    { $add: [{ $ifNull: [countPath, 0] }, 1] },
    1
  );
}

export async function checkListingRateLimit(userId) {
  const settings = await getAppSettings();
  const user = await getAuthUserById(userId);

  if (!user) return { allowed: false, reason: "user_not_found" };
  const status = user.status || (user.banned ? "banned" : "active");
  if (status !== "active") return { allowed: false, reason: status === "banned" ? "banned" : "inactive" };
  if (user.listingLimitOverride != null) return { allowed: true };

  const now = new Date();
  const listingQuota = user.quota?.listing || {};
  let today = listingQuota.today || 0;
  let month = listingQuota.thisMonth || 0;

  if (!listingQuota.todayReset || !isSameDay(new Date(listingQuota.todayReset), now)) today = 0;
  if (!listingQuota.monthReset || !isSameMonth(new Date(listingQuota.monthReset), now)) month = 0;

  if (today >= settings.maxListingsPerDay) return { allowed: false, reason: "daily" };
  if (month >= settings.maxListingsPerMonth) return { allowed: false, reason: "monthly" };

  return { allowed: true, listingsToday: today, listingsThisMonth: month };
}

export async function incrementListingCount(userId) {
  const db = await getMongoDb();
  const filter = authUserIdFilter(userId);
  const now = new Date();
  const currentDayString = now.toISOString().slice(0, 10);
  const currentMonthString = now.toISOString().slice(0, 7);

  await db.collection("user").updateOne(
    filter,
    [
      {
        $set: {
          "quota.listing.today": listingCountIncrementCond(
            "quota.listing.todayReset",
            "quota.listing.today",
            "%Y-%m-%d",
            currentDayString
          ),
          "quota.listing.thisMonth": listingCountIncrementCond(
            "quota.listing.monthReset",
            "quota.listing.thisMonth",
            "%Y-%m",
            currentMonthString
          ),
          "quota.listing.todayReset": now,
          "quota.listing.monthReset": now,
        },
      },
    ]
  );
}

export async function checkReportRateLimit(userId) {
  const limit = (await getAppSettings()).maxReportsPerDay ?? 50;
  const start = new Date();
  start.setUTCHours(0, 0, 0, 0);

  const count = await ModerationReport.countDocuments({
    reporterId: userId,
    autoGenerated: { $ne: true },
    createdAt: { $gte: start },
  });

  if (count < limit) return { allowed: true };

  return { allowed: false, error: "report_limit_exceeded" };
}

export async function enforceUploadRateLimits({ userId, prefix }) {
  if (!env.uploadRateLimit.enabled) return { allowed: true };

  try {
    const ip = await checkUploadIpRateLimit(await getClientIp());
    if (!ip.allowed) return { allowed: false, error: "rate_limit_exceeded", status: 429 };
  } catch {
    return { allowed: false, error: "rate_limit_unavailable", status: 503 };
  }

  if (prefix !== "listings") return { allowed: true };

  const listing = await checkListingRateLimit(userId);
  if (!listing.allowed) {
    if (listing.reason === "banned") {
      return { allowed: false, error: "user_banned", status: 403 };
    }
    if (listing.reason === "inactive") {
      const u = await getAuthUserById(userId);
      const status = u?.status || "inactive";
      return { allowed: false, error: `user_${status}`, status: 403 };
    }
    if (listing.reason === "user_not_found") {
      return { allowed: false, error: "user_not_found", status: 404 };
    }
    return {
      allowed: false,
      error: listing.reason === "monthly" ? "listing_limit_monthly" : "listing_limit_daily",
      status: 429,
    };
  }

  if (!hasRedis()) return { allowed: true };

  try {
    const cap = (await getAppSettings()).maxListingsPerDay * MAX_LISTING_IMAGES;
    if ((await getDailyUploadCount(userId, prefix)) >= cap) {
      return { allowed: false, error: "upload_daily_limit", status: 429 };
    }
  } catch {
    return { allowed: false, error: "rate_limit_unavailable", status: 503 };
  }

  return { allowed: true };
}

export async function recordListingUploadPresign(userId, prefix) {
  if (prefix !== "listings" || !hasRedis()) return;
  try {
    await incrementDailyUploadCount(userId, prefix);
  } catch {
    // Non-fatal.
  }
}
