/** @file Per-user quotas — listings, reports, uploads. */

import { ModerationReport } from "@/models/moderation-report";
import { getAppSettings } from "@/lib/services/settings";
import { getAuthUserById, updateAuthUserById, authUserIdFilter } from "@/lib/auth/users";
import { getClientIp } from "@/lib/request-metadata";
import { env } from "@/config/env";
import { hasRedis, ensureRedisConnection } from "@/lib/redis";
import { checkIpRateLimits } from "./ip";
import { MAX_LISTING_IMAGES } from "@/config/constants/enums";
import { getMongoDb } from "@/config/db";

function isSameDay(a, b) {
  return (
    a.getUTCFullYear() === b.getUTCFullYear() &&
    a.getUTCMonth() === b.getUTCMonth() &&
    a.getUTCDate() === b.getUTCDate()
  );
}

function isSameMonth(a, b) {
  return (
    a.getUTCFullYear() === b.getUTCFullYear() &&
    a.getUTCMonth() === b.getUTCMonth()
  );
}

function uploadDayKey(userId, prefix) {
  const d = new Date();
  const day = `${d.getUTCFullYear()}${String(d.getUTCMonth() + 1).padStart(2, "0")}${String(d.getUTCDate()).padStart(2, "0")}`;
  return `rl:upload:user:${userId}:${prefix}:${day}`;
}

async function dailyUploadCount(key, increment = false) {
  const redis = await ensureRedisConnection();
  if (increment) {
    const n = await redis.incr(key);
    if (n === 1) await redis.expire(key, 172_800);
    return n;
  }
  return Number(await redis.get(key)) || 0;
}

export async function checkListingRateLimit(userId) {
  const settings = await getAppSettings();
  const user = await getAuthUserById(userId);

  if (!user) return { allowed: false, reason: "user_not_found" };
  if (user.banned) return { allowed: false, reason: "banned" };
  if (user.listingLimitOverride != null) return { allowed: true };

  const now = new Date();
  let today = user.listingsToday || 0;
  let month = user.listingsThisMonth || 0;

  if (!user.listingsTodayReset || !isSameDay(new Date(user.listingsTodayReset), now)) today = 0;
  if (!user.listingsMonthReset || !isSameMonth(new Date(user.listingsMonthReset), now)) month = 0;

  if (today >= settings.maxListingsPerDay) return { allowed: false, reason: "daily" };
  if (month >= settings.maxListingsPerMonth) return { allowed: false, reason: "monthly" };

  return { allowed: true, listingsToday: today, listingsThisMonth: month };
}

export async function incrementListingCount(userId) {
  const db = await getMongoDb();
  const filter = authUserIdFilter(userId);
  const now = new Date();
  const currentDayString = now.toISOString().slice(0, 10);
  const currentMonthString = now.toISOString().slice(0, 7);

  await db.collection("user").updateOne(
    filter,
    [
      {
        $set: {
          listingsToday: {
            $cond: {
              if: {
                $and: [
                  { $gt: ["$listingsTodayReset", null] },
                  {
                    $eq: [
                      { $dateToString: { format: "%Y-%m-%d", date: "$listingsTodayReset", timezone: "UTC" } },
                      currentDayString,
                    ],
                  },
                ],
              },
              then: { $add: [{ $ifNull: ["$listingsToday", 0] }, 1] },
              else: 1,
            },
          },
          listingsThisMonth: {
            $cond: {
              if: {
                $and: [
                  { $gt: ["$listingsMonthReset", null] },
                  {
                    $eq: [
                      { $dateToString: { format: "%Y-%m", date: "$listingsMonthReset", timezone: "UTC" } },
                      currentMonthString,
                    ],
                  },
                ],
              },
              then: { $add: [{ $ifNull: ["$listingsThisMonth", 0] }, 1] },
              else: 1,
            },
          },
          listingsTodayReset: now,
          listingsMonthReset: now,
        },
      },
    ]
  );
}

export async function checkReportRateLimit(userId) {
  const limit = (await getAppSettings()).maxReportsPerDay ?? 50;
  const start = new Date();
  start.setUTCHours(0, 0, 0, 0);

  const count = await ModerationReport.countDocuments({
    reporterId: userId,
    autoGenerated: { $ne: true },
    createdAt: { $gte: start },
  });

  if (count < limit) return { allowed: true };

  return { allowed: false, error: "report_limit_exceeded" };
}

export async function enforceUploadRateLimits({ userId, prefix }) {
  if (!env.rateLimit.enabled) return { allowed: true };

  try {
    const ip = await checkIpRateLimits(await getClientIp(), true);
    if (!ip.allowed) return { allowed: false, error: "rate_limit_exceeded", status: 429 };
  } catch {
    return { allowed: false, error: "rate_limit_unavailable", status: 503 };
  }

  if (prefix !== "listings") return { allowed: true };

  const listing = await checkListingRateLimit(userId);
  if (!listing.allowed) {
    if (listing.reason === "banned") {
      return { allowed: false, error: "user_banned", status: 403 };
    }
    if (listing.reason === "user_not_found") {
      return { allowed: false, error: "user_not_found", status: 404 };
    }
    return {
      allowed: false,
      error: listing.reason === "monthly" ? "listing_limit_monthly" : "listing_limit_daily",
      status: 429,
    };
  }

  if (!hasRedis()) return { allowed: true };

  try {
    const cap = (await getAppSettings()).maxListingsPerDay * MAX_LISTING_IMAGES;
    if ((await dailyUploadCount(uploadDayKey(userId, prefix))) >= cap) {
      return { allowed: false, error: "upload_daily_limit", status: 429 };
    }
  } catch {
    return { allowed: false, error: "rate_limit_unavailable", status: 503 };
  }

  return { allowed: true };
}

export async function recordListingUploadPresign(userId, prefix) {
  if (prefix !== "listings" || !hasRedis()) return;
  try {
    await dailyUploadCount(uploadDayKey(userId, prefix), true);
  } catch {
    // Non-fatal.
  }
}
