/**
 * Automatic listing review when crowd reports or system abuse scores warrant it.
 */

import { ModerationReport } from "@/models/moderation-report";
import { Listing } from "@/models/listing";
import { setListingStatus } from "@/lib/listings/status";
import { getAppSettings } from "@/lib/services/settings";
import { countDistinctContributors } from "@/lib/moderation/report-cases";

/**
 * Count open user reports for a listing+reason inside the configured time window.
 *
 * @param {import("mongoose").Types.ObjectId|string} listingId
 * @param {string} reason
 */
export async function countCaseContributorsInWindow(listingId, reason) {
  const settings = await getAppSettings();
  const windowHours = settings.reportAutoReviewWindowHours ?? 168;
  const since = new Date(Date.now() - windowHours * 3_600_000);

  const reports = await ModerationReport.find({
    listingId,
    reason,
    autoGenerated: { $ne: true },
    status: { $in: ["open", "reviewing"] },
    createdAt: { $gte: since },
  })
    .select("reporterId clientIp")
    .lean();

  return {
    contributorCount: countDistinctContributors(reports),
    windowHours,
    minRequired: settings.reportAutoReviewMinReports ?? 3,
  };
}

/**
 * @param {import("mongoose").Types.ObjectId|string} listingId
 */
async function latestSystemAbuseScore(listingId) {
  const report = await ModerationReport.findOne({
    listingId,
    autoGenerated: true,
    reason: "duplicate",
    status: { $in: ["open", "reviewing"] },
  })
    .sort({ createdAt: -1 })
    .select("evidence.riskScore")
    .lean();

  return report?.evidence?.riskScore ?? 0;
}

/**
 * Move a listing to under_review when thresholds are met.
 *
 * @returns {Promise<{ autoReviewed: boolean, contributorCount: number }>}
 */
export async function maybeAutoReviewListing(listingId, reason) {
  const listing = await Listing.findById(listingId);
  if (!listing || ["removed", "resolved", "expired"].includes(listing.status)) {
    return { autoReviewed: false, contributorCount: 0 };
  }

  if (listing.status === "under_review") {
    return { autoReviewed: false, contributorCount: 0 };
  }

  const settings = await getAppSettings();
  const { contributorCount, minRequired } = await countCaseContributorsInWindow(listingId, reason);
  const abuseScore = await latestSystemAbuseScore(listingId);
  const reviewThreshold = settings.abuseReviewThreshold ?? 0.82;

  const crowdThresholdMet = contributorCount >= minRequired;
  const systemThresholdMet = abuseScore >= reviewThreshold;
  const combinedThresholdMet = contributorCount >= 1 && abuseScore >= 0.75;

  if (!crowdThresholdMet && !systemThresholdMet && !combinedThresholdMet) {
    return { autoReviewed: false, contributorCount };
  }

  await setListingStatus(listing, "under_review");

  const note = systemThresholdMet
    ? `System abuse score ${Math.round(abuseScore * 100)}%`
    : combinedThresholdMet
      ? `${contributorCount} report(s) + abuse score ${Math.round(abuseScore * 100)}%`
      : `${contributorCount} independent reports within window`;

  await ModerationReport.updateMany(
    { listingId, reason, status: "open" },
    {
      $set: { status: "reviewing" },
      $push: {
        auditLog: {
          action: "auto_under_review",
          by: "system",
          note,
          at: new Date(),
        },
      },
    }
  );

  return { autoReviewed: true, contributorCount };
}
