/**
 * Report case helpers — group reports by listing + reason for moderation queues.
 *
 * A "case" is all reports sharing the same listingId and reason. Admins resolve
 * cases as a unit; individual submissions remain visible for audit.
 */

import mongoose from "mongoose";
import { unstable_cache } from "next/cache";
import { ModerationReport } from "@/models/moderation-report";
import { Listing, attachListingPublicId } from "@/models/listing";
import { ADMIN_PAGE_SIZE } from "@/config/constants/platform";

export const MODERATION_CASES_TAG = "moderation-cases";

/** Report statuses that still need moderator attention. */
export const OPEN_REPORT_STATUSES = ["open", "reviewing"];

const openReportMatch = { status: { $in: OPEN_REPORT_STATUSES } };

/** Stable case identifier used in URLs and audit logs. */
export function buildReportCaseKey(listingId, reason) {
  return `${listingId}:${reason}`;
}

/** Admin case detail URL — uses listing public ID, not MongoDB `_id`. */
export function reportCasePath(listingPublicId, reason) {
  return `/admin/reports/${listingPublicId}/${encodeURIComponent(reason)}`;
}

/**
 * Count distinct contributors for auto-review.
 * Each IP counts once (mitigates sock-puppet floods); falls back to reporterId when IP is missing.
 */
export function countDistinctContributors(reports) {
  const seenIps = new Set();
  let count = 0;

  for (const report of reports) {
    const key = report.clientIp?.trim() || report.reporterId;
    if (seenIps.has(key)) continue;
    seenIps.add(key);
    count += 1;
  }

  return count;
}

/**
 * Build the MongoDB match stage for case list filters.
 * @param {Record<string, string | undefined>} sp
 */
export function buildReportCaseMatch(sp) {
  const match = {};

  if (sp.reason) match.reason = sp.reason;
  if (sp.listingId) {
    match.listingId = mongoose.Types.ObjectId.isValid(sp.listingId)
      ? new mongoose.Types.ObjectId(sp.listingId)
      : sp.listingId;
  }

  const status = sp.status || "open";
  if (status === "all") {
    // No status constraint — include every case.
  } else if (status === "open") {
    match.status = { $in: OPEN_REPORT_STATUSES };
  } else {
    match.status = status;
  }

  const q = sp.q?.trim();
  if (q) {
    match.$or = [
      { details: { $regex: q, $options: "i" } },
      { reason: { $regex: q, $options: "i" } },
    ];
  }

  return match;
}

/** Aggregate open (or filtered) reports into moderation cases. */
export async function queryReportCases(sp) {
  const match = buildReportCaseMatch(sp);
  const page = Math.max(1, Number(sp.page) || 1);
  const skip = (page - 1) * ADMIN_PAGE_SIZE;

  const [grouped, totalResult] = await Promise.all([
    ModerationReport.aggregate([
      { $match: match },
      {
        $group: {
          _id: { listingId: "$listingId", reason: "$reason" },
          reportCount: { $sum: 1 },
          reporterIds: { $addToSet: "$reporterId" },
          clientIps: { $addToSet: "$clientIp" },
          latestAt: { $max: "$createdAt" },
          oldestAt: { $min: "$createdAt" },
          statuses: { $addToSet: "$status" },
          hasAutoGenerated: { $max: { $cond: ["$autoGenerated", 1, 0] } },
        },
      },
      { $sort: { latestAt: -1 } },
      { $skip: skip },
      { $limit: ADMIN_PAGE_SIZE },
    ]),
    ModerationReport.aggregate([
      { $match: match },
      { $group: { _id: { listingId: "$listingId", reason: "$reason" } } },
      { $count: "total" },
    ]),
  ]);

  const total = totalResult[0]?.total ?? 0;
  const listingIds = [...new Set(grouped.map((g) => String(g._id.listingId)))];

  const listings = listingIds.length
    ? await Listing.find({ _id: { $in: listingIds } })
        .select("petType color type status reportCount userId")
        .lean()
    : [];

  const listingMap = Object.fromEntries(listings.map((l) => [String(l._id), l]));

  const items = grouped.map((g) => {
    const listingId = String(g._id.listingId);
    const ips = (g.clientIps || []).filter(Boolean);
    return {
      listingId,
      reason: g._id.reason,
      caseKey: buildReportCaseKey(listingId, g._id.reason),
      reportCount: g.reportCount,
      uniqueReporters: g.reporterIds?.length ?? 0,
      uniqueIps: ips.length || g.reporterIds?.length || 0,
      latestAt: g.latestAt,
      oldestAt: g.oldestAt,
      statuses: g.statuses || [],
      hasAutoGenerated: Boolean(g.hasAutoGenerated),
      listing: listingMap[listingId] ? attachListingPublicId(listingMap[listingId]) : null,
    };
  });

  return { total, items, showing: items.length, page };
}

/**
 * Open report totals per listing — source of truth for admin listing flags.
 * @param {import("mongoose").Types.ObjectId[]|string[]} listingIds
 * @returns {Promise<Record<string, { openReportCount: number, openCaseCount: number }>>}
 */
export async function getOpenReportStatsByListingIds(listingIds) {
  if (!listingIds.length) return {};

  const objectIds = listingIds.map((id) =>
    mongoose.Types.ObjectId.isValid(id) ? new mongoose.Types.ObjectId(id) : id
  );

  const [reportTotals, caseTotals] = await Promise.all([
    ModerationReport.aggregate([
      { $match: { listingId: { $in: objectIds }, ...openReportMatch } },
      { $group: { _id: "$listingId", openReportCount: { $sum: 1 } } },
    ]),
    ModerationReport.aggregate([
      { $match: { listingId: { $in: objectIds }, ...openReportMatch } },
      { $group: { _id: { listingId: "$listingId", reason: "$reason" } } },
      { $group: { _id: "$_id.listingId", openCaseCount: { $sum: 1 } } },
    ]),
  ]);

  const stats = {};
  for (const row of reportTotals) {
    const key = String(row._id);
    stats[key] = { openReportCount: row.openReportCount, openCaseCount: 0 };
  }
  for (const row of caseTotals) {
    const key = String(row._id);
    stats[key] = {
      openReportCount: stats[key]?.openReportCount ?? 0,
      openCaseCount: row.openCaseCount,
    };
  }
  return stats;
}

/** Listing IDs that currently have at least one open report. */
export async function getListingIdsWithOpenReports() {
  return ModerationReport.distinct("listingId", openReportMatch);
}

async function countOpenReportCasesUncached() {
  const result = await ModerationReport.aggregate([
    { $match: openReportMatch },
    { $group: { _id: { listingId: "$listingId", reason: "$reason" } } },
    { $count: "total" },
  ]);
  return result[0]?.total ?? 0;
}

/** Count distinct open moderation cases (listing + reason groups). Cached 60s. */
export const countOpenReportCases = unstable_cache(
  countOpenReportCasesUncached,
  ["moderation-open-cases"],
  { revalidate: 60, tags: [MODERATION_CASES_TAG] }
);

/** Latest open cases for dashboard widgets. */
export async function getRecentOpenReportCases(limit = 5) {
  const grouped = await ModerationReport.aggregate([
    { $match: openReportMatch },
    {
      $group: {
        _id: { listingId: "$listingId", reason: "$reason" },
        latestAt: { $max: "$createdAt" },
        reportCount: { $sum: 1 },
      },
    },
    { $sort: { latestAt: -1 } },
    { $limit: limit },
  ]);

  const listingIds = grouped.map((g) => g._id.listingId);
  const listings = listingIds.length
    ? await Listing.find({ _id: { $in: listingIds } }).select("petType color").lean()
    : [];
  const listingMap = Object.fromEntries(listings.map((l) => [String(l._id), l]));

  return grouped.map((g) => ({
    listingId: String(g._id.listingId),
    reason: g._id.reason,
    latestAt: g.latestAt,
    reportCount: g.reportCount,
    listing: listingMap[String(g._id.listingId)]
      ? attachListingPublicId(listingMap[String(g._id.listingId)])
      : null,
  }));
}

/**
 * Case detail payload — listing and reports fetched in parallel (no populate N+1).
 * @returns {Promise<{ listing: object | null, reports: object[] }>}
 */
export async function getReportCaseData(listingId, reason) {
  const [listing, reports] = await Promise.all([
    Listing.findById(listingId).select("petType color type status userId").lean(),
    ModerationReport.find({ listingId, reason })
      .sort({ createdAt: -1 })
      .select(
        "reporterId details evidence status resolution auditLog autoGenerated clientIp userAgent createdAt"
      )
      .lean(),
  ]);

  return {
    listing: listing ? attachListingPublicId(listing) : null,
    reports,
  };
}

/** Open reports in a case — the set admins resolve together. */
export async function getOpenCaseReports(listingId, reason) {
  return ModerationReport.find({
    listingId,
    reason,
    status: { $in: OPEN_REPORT_STATUSES },
  }).sort({ createdAt: -1 });
}
