"use client";

import Link from "next/link";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { AdminStatusBadge } from "@/components/admin/status-badge";
import { Badge } from "@/components/ui/badge";
import { formatDateTimeFull } from "@/lib/format";

function ReportEntryDetails({ report, reporter }) {
  const isSystem = report.reporterId === "system" || report.autoGenerated;

  return (
    <div className="grid gap-4 border-t pt-4 lg:grid-cols-[1fr_240px]">
      <div className="min-w-0 space-y-4">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Explanation
          </p>
          {report.details ? (
            <p className="mt-1.5 text-sm leading-relaxed">{report.details}</p>
          ) : (
            <p className="mt-1.5 text-sm text-muted-foreground">No additional details provided.</p>
          )}
        </div>

        {report.evidence?.riskScore != null ? (
          <div className="rounded-lg border bg-muted/20 p-3">
            <div className="flex flex-wrap items-center gap-2">
              <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                Risk assessment
              </p>
              <Badge variant={report.evidence.riskScore >= 0.82 ? "destructive" : "secondary"}>
                {Math.round(report.evidence.riskScore * 100)}% risk
              </Badge>
            </div>

            {report.evidence.signals?.length > 0 ? (
              <table className="mt-3 w-full text-xs">
                <thead>
                  <tr className="text-left text-muted-foreground">
                    <th className="pb-1 pe-2">Signal</th>
                    <th className="pb-1 pe-2">Weight</th>
                    <th className="pb-1">Detail</th>
                  </tr>
                </thead>
                <tbody>
                  {report.evidence.signals.map((s, i) => (
                    <tr key={i} className="border-t border-border/50">
                      <td className="py-1.5 pe-2 font-mono">{s.code}</td>
                      <td className="py-1.5 pe-2 tabular-nums">{Math.round(s.weight * 100)}%</td>
                      <td className="py-1.5 text-muted-foreground">{s.detail}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : null}

            {report.evidence.relatedListings?.length > 0 ? (
              <div className="mt-3 space-y-1.5">
                <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                  Related ads
                </p>
                <ul className="space-y-1 text-sm">
                  {report.evidence.relatedListings.map((rel, i) => (
                    <li key={i}>
                      <Link
                        href={`/admin/listings/${rel.publicId}`}
                        className="text-primary hover:underline"
                      >
                        {rel.listingType} · {rel.relationship}
                      </Link>
                      <span className="text-muted-foreground">
                        {" "}
                        — {Math.round((rel.score || 0) * 100)}% · {rel.listingStatus}
                      </span>
                    </li>
                  ))}
                </ul>
              </div>
            ) : null}
          </div>
        ) : null}

        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Audit log
          </p>
          {report.auditLog?.length > 0 ? (
            <div className="mt-2 space-y-2">
              {report.auditLog.map((entry, i) => (
                <div key={i} className="rounded-md border bg-muted/20 px-3 py-2 text-sm">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge variant="outline" className="text-xs">
                      {entry.action}
                    </Badge>
                    <span className="text-xs text-muted-foreground">
                      {formatDateTimeFull(entry.at)}
                    </span>
                  </div>
                  {entry.note ? (
                    <p className="mt-1.5 text-muted-foreground">{entry.note}</p>
                  ) : null}
                </div>
              ))}
            </div>
          ) : (
            <p className="mt-2 text-sm text-muted-foreground">No audit entries yet.</p>
          )}
        </div>
      </div>

      <aside className="space-y-3 rounded-lg border bg-muted/20 p-3 text-sm lg:self-start">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
            Reporter
          </p>
          {isSystem ? (
            <p className="mt-1.5 font-medium">System</p>
          ) : reporter ? (
            <div className="mt-1.5 space-y-1">
              <Link
                href={`/admin/users/${reporter.publicId}`}
                className="font-medium text-primary hover:underline"
              >
                {reporter.name || reporter.email || reporter.id}
              </Link>
              {reporter.email ? (
                <p className="text-xs text-muted-foreground">{reporter.email}</p>
              ) : null}
              {reporter.banned ? (
                <Badge variant="destructive" className="text-xs">
                  Banned
                </Badge>
              ) : null}
            </div>
          ) : (
            <p className="mt-1.5 break-all font-mono text-xs">{report.reporterId}</p>
          )}
        </div>

        <dl className="space-y-3 text-xs">
          {report.clientIp ? (
            <div>
              <dt className="font-medium uppercase tracking-wide text-muted-foreground">
                IP address
              </dt>
              <dd className="mt-1 font-mono">{report.clientIp}</dd>
            </div>
          ) : null}
          {report.userAgent ? (
            <div>
              <dt className="font-medium uppercase tracking-wide text-muted-foreground">
                User agent
              </dt>
              <dd className="mt-1 break-all leading-relaxed">{report.userAgent}</dd>
            </div>
          ) : null}
          <div>
            <dt className="font-medium uppercase tracking-wide text-muted-foreground">
              Submitted
            </dt>
            <dd className="mt-1">{formatDateTimeFull(report.createdAt)}</dd>
          </div>
        </dl>
      </aside>
    </div>
  );
}

/** Collapsible list of reports in a case — collapsed row shows status + reporter + date. */
export function ReportEntriesList({ reports, reportersById }) {
  if (!reports.length) {
    return <p className="text-sm text-muted-foreground">No reports in this case.</p>;
  }

  return (
    <Accordion type="multiple" className="space-y-2">
      {reports.map((report) => {
        const id = report._id;
        const reporter = reportersById[report.reporterId] ?? null;
        const isSystem = report.reporterId === "system" || report.autoGenerated;
        const reporterLabel = isSystem
          ? "System"
          : reporter?.name || reporter?.email || report.reporterId;

        return (
          <AccordionItem
            key={id}
            value={id}
            className="rounded-lg border border-border px-4 last:border-b"
          >
            <AccordionTrigger className="py-3 hover:no-underline">
              <div className="flex min-w-0 flex-1 flex-wrap items-center gap-2 pe-2 text-start">
                <AdminStatusBadge value={report.status} />
                {report.autoGenerated ? (
                  <Badge variant="secondary" className="text-xs">
                    Auto
                  </Badge>
                ) : null}
                {report.resolution ? (
                  <Badge variant="outline" className="text-xs">
                    {report.resolution}
                  </Badge>
                ) : null}
                <span className="truncate text-sm font-medium">{reporterLabel}</span>
                <time className="text-xs text-muted-foreground" dateTime={report.createdAt}>
                  {formatDateTimeFull(report.createdAt)}
                </time>
              </div>
            </AccordionTrigger>
            <AccordionContent className="pb-4">
              <ReportEntryDetails report={report} reporter={reporter} />
            </AccordionContent>
          </AccordionItem>
        );
      })}
    </Accordion>
  );
}
