/** @file Shared system ModerationReport upsert used by safety and abuse pipelines. */

import { ModerationReport } from "@/models/moderation-report";

/**
 * Build a short human-readable summary for the moderator queue.
 *
 * @param {object} params
 * @param {string} params.label Prefix label (e.g. "Automated content safety")
 * @param {number} [params.score] Optional risk/score 0–1 included in the summary
 * @param {Array<{ code: string, weight: number }>} params.signals
 * @returns {string}
 */
export function buildSignalDetailsSummary({ label, score, signals }) {
  const top = (signals || [])
    .slice(0, 5)
    .map((s) => `${s.code} (${Math.round(s.weight * 100)}%)`)
    .join("; ");

  if (typeof score === "number") {
    const pct = Math.round(score * 100);
    return `${label}: ${pct}% risk. Signals: ${top || "none"}.`;
  }

  return `${label}: ${top || "none"}.`;
}

/**
 * Create or update an open system-generated moderation report for a listing.
 *
 * @param {object} params
 * @param {import("mongoose").Document} params.listing
 * @param {string} params.reason Report reason enum value (`inappropriate` | `duplicate` | …)
 * @param {object} params.evidence Structured evidence payload
 * @param {string} params.details Human-readable details
 * @param {string} params.auditAction Audit log action key
 * @param {boolean} [params.save=true] Persist listing.reportCount bump immediately
 * @returns {Promise<void>}
 */
export async function upsertSystemModerationReport({
  listing,
  reason,
  evidence,
  details,
  auditAction,
  save = true,
}) {
  const existing = await ModerationReport.findOne({
    listingId: listing._id,
    reporterId: "system",
    reason,
    status: { $in: ["open", "reviewing"] },
  });

  if (existing) {
    existing.evidence = evidence;
    existing.details = details;
    const note =
      typeof evidence?.riskScore === "number"
        ? `Updated assessment — risk ${Math.round(evidence.riskScore * 100)}%`
        : details;
    existing.auditLog.push({
      action: auditAction,
      by: "system",
      note,
      at: new Date(),
    });
    await existing.save();
    return;
  }

  await ModerationReport.create({
    listingId: listing._id,
    reporterId: "system",
    reason,
    details,
    evidence,
    status: "open",
    autoGenerated: true,
    auditLog: [{ action: auditAction, by: "system", note: details }],
  });

  listing.reportCount = (listing.reportCount || 0) + 1;
  if (save) {
    await listing.save();
  }
}
