import Link from "next/link";
import { connectDB } from "@/config/db";
import { requireStaff } from "@/lib/auth/session";
import { reportCasePath } from "@/lib/moderation/report-cases";
import { listingPath } from "@/lib/paths";
import { routing } from "@/i18n/routing";
import { queryReportCases } from "@/lib/moderation/report-cases";
import { AdminPageHeader } from "@/components/admin/page-header";
import { AdminFilterToolbar } from "@/components/admin/filter-toolbar";
import { AdminResultSummary } from "@/components/admin/result-summary";
import { AdminStatusBadge } from "@/components/admin/status-badge";
import { REPORT_REASONS } from "@/config/constants/enums";
import {
  AdminDataTable,
  AdminEmptyState,
  AdminTableBody,
  AdminTableHead,
  AdminTableRow,
  AdminTableTd,
  AdminTableTh,
} from "@/components/admin/data-table";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { formatDateTimeFull } from "@/lib/format";
import { Eye, Users } from "lucide-react";

export default async function AdminReportsPage({ searchParams }) {
  await requireStaff();
  await connectDB();

  const sp = await searchParams;
  const { total, items, showing } = await queryReportCases(sp);
  const listingFilter = sp.listingId;
  const statusFilter = sp.status || "open";

  return (
    <div className="space-y-6">
      <AdminPageHeader
        title="Reports"
        description="Moderation queue grouped by listing and reason — resolve related reports as one case."
      />

      {listingFilter ? (
        <div className="rounded-lg border bg-muted/30 px-4 py-3 text-sm">
          Filtered by listing <code className="text-xs">{listingFilter}</code>
          {total === 0 && statusFilter === "open" ? (
            <>
              {" "}
              — no open cases.{" "}
              <Link
                href={`/admin/reports?listingId=${listingFilter}&status=all`}
                className="text-primary hover:underline"
              >
                View all report history
              </Link>
            </>
          ) : null}
          {" · "}
          <Link href="/admin/reports" className="text-primary hover:underline">
            Clear filter
          </Link>
        </div>
      ) : null}

      <AdminFilterToolbar
        searchPlaceholder="Search reason or details…"
        filters={[
          {
            key: "status",
            label: "Status",
            defaultValue: "open",
            clearOnAll: false,
            options: [
              { value: "open", label: "Open" },
              { value: "reviewing", label: "Under review" },
              { value: "resolved", label: "Resolved" },
              { value: "dismissed", label: "Dismissed" },
            ],
          },
          {
            key: "reason",
            label: "Reason",
            options: REPORT_REASONS.map((r) => ({ value: r, label: r })),
          },
        ]}
      />

      <AdminResultSummary total={total} showing={showing} />

      <AdminDataTable>
        <AdminTableHead>
          <AdminTableTh>Case</AdminTableTh>
          <AdminTableTh>Listing</AdminTableTh>
          <AdminTableTh>Reports</AdminTableTh>
          <AdminTableTh>Latest</AdminTableTh>
          <AdminTableTh>Actions</AdminTableTh>
        </AdminTableHead>
        <AdminTableBody>
          {items.length === 0 ? (
            <AdminEmptyState message="No report cases match your filters" colSpan={5} />
          ) : (
            items.map((c) => {
              const caseHref = c.listing?.publicId
                ? reportCasePath(c.listing.publicId, c.reason)
                : null;
              return (
                <AdminTableRow key={c.caseKey}>
                  <AdminTableTd>
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge className="capitalize">{c.reason}</Badge>
                      {c.hasAutoGenerated ? <Badge variant="secondary">includes auto</Badge> : null}
                      {c.statuses.map((s) => (
                        <AdminStatusBadge key={s} value={s} />
                      ))}
                    </div>
                  </AdminTableTd>
                  <AdminTableTd>
                    {c.listing ? (
                      <div>
                        <p className="font-medium capitalize">
                          {c.listing.petType} — {c.listing.color}
                        </p>
                        <div className="mt-1 flex flex-wrap gap-2 text-xs">
                          <AdminStatusBadge value={c.listing.status} />
                          <a
                            href={listingPath(c.listing.publicId, routing.defaultLocale)}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="text-primary hover:underline"
                          >
                            View ad
                          </a>
                        </div>
                      </div>
                    ) : (
                      <span className="text-muted-foreground">Listing unavailable</span>
                    )}
                  </AdminTableTd>
                  <AdminTableTd>
                    <div className="flex items-center gap-2 text-sm">
                      <Badge variant="outline">{c.reportCount} total</Badge>
                      <span className="inline-flex items-center gap-1 text-xs text-muted-foreground">
                        <Users className="size-3" />
                        {c.uniqueReporters} users · {c.uniqueIps} IPs
                      </span>
                    </div>
                  </AdminTableTd>
                  <AdminTableTd className="text-xs text-muted-foreground">
                    {formatDateTimeFull(c.latestAt)}
                  </AdminTableTd>
                  <AdminTableTd>
                    {caseHref ? (
                      <Button size="sm" variant="outline" asChild>
                        <Link href={caseHref}>
                          <Eye className="size-3.5" />
                          Review case
                        </Link>
                      </Button>
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </AdminTableTd>
                </AdminTableRow>
              );
            })
          )}
        </AdminTableBody>
      </AdminDataTable>
    </div>
  );
}
