/** @file User or system moderation report with evidence and audit trail. */

import mongoose from "mongoose";
import { REPORT_REASONS, REPORT_STATUSES } from "@/config/constants/enums";

const auditEntrySchema = new mongoose.Schema(
  {
    action: String,
    by: String,
    note: String,
    at: { type: Date, default: Date.now },
  },
  { _id: false }
);

const evidenceSignalSchema = new mongoose.Schema(
  {
    code: { type: String, required: true },
    weight: { type: Number, required: true },
    detail: { type: String, default: "" },
  },
  { _id: false }
);

const relatedListingSchema = new mongoose.Schema(
  {
    listingId: { type: mongoose.Schema.Types.ObjectId, ref: "Listing", required: true },
    publicId: { type: String, required: true },
    relationship: { type: String, enum: ["duplicate_of", "similar_to"], required: true },
    score: { type: Number, default: 0 },
    listingType: String,
    listingStatus: String,
  },
  { _id: false }
);

const evidenceSchema = new mongoose.Schema(
  {
    riskScore: { type: Number, default: 0 },
    signals: [evidenceSignalSchema],
    relatedListings: [relatedListingSchema],
  },
  { _id: false }
);

const moderationReportSchema = new mongoose.Schema(
  {
    listingId: { type: mongoose.Schema.Types.ObjectId, ref: "Listing", required: true, index: true },
    reporterId: { type: String, required: true, index: true },
    reason: { type: String, enum: REPORT_REASONS, required: true },
    details: { type: String, default: "" },
    evidence: evidenceSchema,
    status: { type: String, enum: REPORT_STATUSES, default: "open", index: true },
    assignedTo: { type: String },
    resolution: { type: String },
    auditLog: [auditEntrySchema],
    autoGenerated: { type: Boolean, default: false },
    clientIp: { type: String, default: "" },
    userAgent: { type: String, default: "" },
  },
  { timestamps: true }
);

moderationReportSchema.index(
  { listingId: 1, reporterId: 1 },
  { unique: true, partialFilterExpression: { autoGenerated: false } }
);

moderationReportSchema.index({ listingId: 1, reason: 1, status: 1, createdAt: -1 });

export const ModerationReport =
  mongoose.models.ModerationReport || mongoose.model("ModerationReport", moderationReportSchema);
